### ISSUE TITLE
ERRO DE CONSISTENCIA:   DADOS INCONSISTENTES - 0840 (6)

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [brenooandrade/api-php-bradesco-boletos#1]
Estou com esse problema ao fazer a requisição alguém já teve esse problema?

**Comment by brenooandrade** [comment]
Boa tarde Junior, acredito que você esqueceu de anexar o erro, pode anexar por gentileza?

**Comment by marquesjuniorpalmas** [comment]
![image](https://user-images.githubusercontent.com/4973483/217072048-90f0e452-1532-4cf7-a88a-af339dad5596.png)


Segue a imagem do erro, outra dúvida é o gerente normalmente precisa habilitar qual serviço para funcionar o registro automatico?

**Comment by brenooandrade** [comment]
A Rejeição ERRO DE CONSISTENCIA: DADOS INCONSISTENTES - 0840 geralmente ocorre nos momentos iniciais da geração de boletos na modalidade WS.

Normalmente este erro está ligado quando existe a alguma informação que está cadastrada na aplicação que seja divergente da cadastrada ou liberada pelo banco, por mínima que seja a diferença das informações cadastradas na aplicação e as disponibilizadas pelo banco, todas elas devem estar de acordo umas com as outras.

A maioria dos casos são algumas informações simples, como por exemplo o código da carteira ou algum DV da conta ou agência.

**Como podemos corrigir?**

Para que este problema não ocorra, é necessário sempre verificar se os seus dados cadastrados na aplicação, estão de acordo com o que o banco solicita.

Caso tenha qualquer dúvida sobre o cenário explicado ou se quiser conhecer nossas soluções voltadas a automatização na geração de boletos, estaremos sempre à disposição, será um prazer ajudar!

Fonte:

https://forum.casadodesenvolvedor.com.br/topic/5911-como-corrigir-a-rejei%C3%A7%C3%A3o-erro-de-consistencia-dados-inconsistentes-0840-6/

**Comment by brenooandrade** [comment]
Junior, sobre o serviço a ser habilitado se eu não me engano seria o registro de cobranças por Webservice no Bradesco NET Empresas, eu não me lembro ao certo o procedimento pois não trabalho na empresa que fazia essa integração mais, porém com essas informações seu gerente já vai conseguir te ajudar.

**Comment by brenooandrade** [comment]
Seguem alguns contatos que podem te ajudar a alinhar esses detalhes da ativação de sua conta:

Atendimento Registro Online
suportewebservice@bradesco.com.br
atendimentoregistroonline@7comm.com.br

Estou fechando a issue, pois não se trata de problemas no código da API disponibilizada.
